"""Sheet music detection constants."""

MASK_BACKGROUND = 0
MASK_FOREGROUND = 255

BLUR_KERNEL_SIZE = (5, 5)

STAFF_LINE_KERNEL_WIDTH_FRAC = 1 / 12
STAFF_LINE_KERNEL_MIN_WIDTH = 25

LINE_DETECTION_MIN_RATIO = 0.35

LINE_CLUSTER_MAX_GAP = 1

LINES_PER_STAFF = 5
STAFF_SPACING_TOLERANCE_FRAC = 0.35
STAFF_SPACING_TOLERANCE_MIN = 2.0

STAFF_VERTICAL_PADDING_FRAC = 2.0

LINE_EXTENT_HALF_WINDOW = 1

STAFF_RECONSTRUCTION_WIDTH_FRAC = 1 / 30

STAFF_ERASE_BAND_FRAC = 0.2

SLIT_REPAIR_KERNEL_MIN = 3
SLIT_REPAIR_KERNEL_MAX = 7
SLIT_REPAIR_BAND_FRAC = 0.1

NOTE_ADAPTIVE_BLOCK_SIZE = 15
NOTE_ADAPTIVE_C = -2

NOTEHEAD_KERNEL_DIAMETER_FRAC = 0.45
NOTEHEAD_KERNEL_MIN = 3

NOTEHEAD_CLEANUP_KERNEL = (3, 3)

NOTE_MIN_AREA_FRAC = 0.08
NOTE_MAX_AREA_FRAC = 1.8
NOTE_MIN_SIZE_FRAC = 0.35
NOTE_MAX_SIZE_FRAC = 1.9
NOTE_MIN_ASPECT = 0.45
NOTE_MAX_ASPECT = 2.2

NOTE_TINY_AREA_FRAC = 0.22

NOTE_MERGE_DISTANCE_FRAC = 0.75

# Bias for notehead center being above geometric center (ink pulls down)
STEP_ROUND_UP_THRESHOLD = 0.58

STEP_CONFIDENCE_HIGH = 0.20
STEP_CONFIDENCE_MEDIUM = 0.40

HOLLOW_NOTE_Y_OFFSET_FRAC = 0.15

FILL_ELLIPSE_X_RADIUS_FRAC = 0.36
FILL_ELLIPSE_Y_RADIUS_FRAC = 0.28
FILL_RATIO_THRESHOLD = 0.55

WHOLE_NOTE_FILL_RATIO_MAX = 0.35

STEM_X_RADIUS_FRAC = 0.85
STEM_Y_RADIUS_FRAC = 2.6
STEM_MIN_RUN_FRAC = 1.2

DUPLICATE_X_TOLERANCE_FRAC = 1.45
DUPLICATE_Y_TOLERANCE_FRAC = 0.75
DUPLICATE_MAX_STEP_DIFF = 1

HOLLOW_SPLIT_X_TOLERANCE_FRAC = 1.8
HOLLOW_SPLIT_INK_RATIO_MAX = 0.30

CLEF_ROI_WIDTH_FRAC = 0.42

CLEF_MIN_CONFIDENCE = 0.15
# treble wins if score is within this margin of bass
CLEF_TIE_MARGIN = 0.06

CLEF_TRIM_WHITE_THRESH = 248

CLEF_MATCH_SCALES = (0.78, 0.88, 0.95, 1.0)

ACCIDENTAL_SCALES = (0.35, 0.5, 0.65, 0.8)
ACCIDENTAL_MATCH_THRESHOLD = 0.50

ACCIDENTAL_MIN_DISTANCE_FRAC = 0.55

ACCIDENTAL_GEOMETRIC_MIN_HEIGHT_FRAC = 1.8
ACCIDENTAL_GEOMETRIC_MIN_AREA_FRAC = 0.18

SHARP_MIN_TALL_CLUSTERS = 2
FLAT_TALL_CLUSTERS = 1
TALL_COLUMN_THRESHOLD_FRAC = 0.75

BAR_SEARCH_LEFT_SKIP_FRAC = 5.0
BAR_SEARCH_LEFT_SKIP_OTHER_FRAC = 2.0

BAR_CLOSE_KERNEL_HEIGHT_FRAC = 2.0
BAR_CLOSE_KERNEL_MIN = 5

BAR_MIN_HEIGHT_FRAC = 0.4
BAR_MIN_DENSITY = 0.55
BAR_MAX_WIDTH_FRAC = 0.6
BAR_DOUBLE_MIN_WIDTH_FRAC = 1.0

BAR_RIGHT_MARGIN_FRAC = 2.0
BAR_LEFT_MARGIN_FRAC = 4.0
BAR_LEFT_RELAXED_EXTRA_FRAC = 0.7

BAR_MERGE_DISTANCE_FRAC = 0.5
BAR_PAIR_GAP_FRAC = 1.5

REPEAT_DOT_SEARCH_WIDTH_FRAC = 1.8
REPEAT_DOT_BAR_GAP_FRAC = 0.25
REPEAT_DOT_MIN_AREA_FRAC = 0.04
REPEAT_DOT_MAX_AREA_FRAC = 0.80
REPEAT_DOT_MAX_SIZE_FRAC = 0.95
REPEAT_DOT_Y_TOLERANCE_FRAC = 0.65
REPEAT_DOT_X_ALIGNMENT_FRAC = 0.85

MEASURE_HEADER_WIDTH_FRAC = 5.2
MEASURE_FIRST_STAFF_HEADER_FRAC = 7.0

BAR_TRIM_FRAC = 0.25

MIN_MEASURE_WIDTH = 4

EVENT_X_TOLERANCE = 5

COMPACT_GAP_MIN_FRAC = 1.2
COMPACT_GAP_MAX_FRAC = 3.6
COMPACT_RUN_MIN_LENGTH = 4

BEAM_X_SPAN_MIN_FRAC = 0.5
BEAM_DENSITY_THRESHOLD_FRAC = 0.15
BEAM_INK_SPAN_MIN_FRAC = 0.20
BEAM_CONTINUITY_MIN_FRAC = 0.8

STEM_DIR_Y_RADIUS_FRAC = 2.5
STEM_DIR_X_RADIUS_FRAC = 0.6
STEM_DIR_RATIO_THRESHOLD = 1.5

TIME_SIG_SCALE_FACTOR = 10.0
TIME_SIG_BORDER = 8

PSM_UNIFORM_BLOCK = 6
PSM_SINGLE_CHAR = 10
PSM_SINGLE_WORD = 8

TIME_SIG_DIGITS = "0123456789"
TIME_SIG_COMMON_TIME = "Cc"

COMMON_TIME_CHAR = "C"

DEFAULT_TITLE = "Sheet Music"
DEFAULT_METER = "4/4"
DEFAULT_UNIT_NOTE_LENGTH = "1/4"
DEFAULT_KEY = "C"
DEFAULT_TEMPO_QPM = 120
